### ISSUE TITLE
Where is the img_rotate.py?

### ISSUE THREAD

**Issue by nobody0702** [kylefox/python-image-orientation-patch#7]
![image](https://cloud.githubusercontent.com/assets/5228598/23785421/98408962-05a2-11e7-9c20-41a8a4f60e2f.png)

**Comment by nobody0702** [comment]
![ak1nns xmkdz8 ui5 j pm](https://cloud.githubusercontent.com/assets/5228598/23785915/f70ed2b2-05a4-11e7-8b4a-1ce9aaeca441.png)
I write my won script img_rotate.py. But it seems that it doesn't work, neither

**Comment by kylefox** [comment]
If you installed with pip: `pip install img_rotate`

You _should_ be able to just use the `img_rotate` command directly:

`img_rotate IMG_0607.JPG`

(It appears the README is slightly outdated.)

Please not you must have [PIL](https://pypi.python.org/pypi/PIL) installed.

**Comment by nobody0702** [comment]
![rr s71zudo0m pxnz noi](https://cloud.githubusercontent.com/assets/5228598/23828473/9d090dcc-070d-11e7-93a2-09bb4ac965c4.png)
Thanks for answering. But still an error.
