### ISSUE TITLE
Final image has black vertical bands on both sides.

### ISSUE THREAD

**Issue by evinw** [kylefox/python-image-orientation-patch#8]
Final image has black vertical bands on both sides.

**Comment by kylefox** [comment]
Can you please attach the image file(s) you're using and describe how you're performing the operation (command line, python API, etc)?

**Comment by TZanke** [comment]
This is fixed in https://github.com/kylefox/python-image-orientation-patch/commit/0cc4fd651f3ab3161bb13954f6a6f690afc6dad7

please build your own package of master, or @kylefox please upload current master as new version to pypi

**Comment by ghost** [comment]
> please build your own package of master, or @kylefox please upload current master as new version to pypi

When is the next release due?

**Comment by kylefox** [comment]
@gregorni This project is no longer active.
